// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logcat} from '../models';
import {build} from '../models';
import {workspace} from '../models';
import {main} from '../models';
import {ai} from '../models';
import {storage} from '../models';
import {adb} from '../models';

export function AnalyzeLogs(arg1:Array<logcat.LogEntry>):Promise<Array<logcat.AnalysisResult>>;

export function BuildDebug(arg1:string):Promise<build.BuildResult>;

export function BuildInstallLaunch(arg1:workspace.ProjectConfig):Promise<main.BuildInstallLaunchResult>;

export function ClearLogs():Promise<void>;

export function CopyAIContext(arg1:string,arg2:ai.AIContextOptions):Promise<void>;

export function DeleteFilterPreset(arg1:string):Promise<workspace.AppConfig>;

export function DeleteWorkspace(arg1:string):Promise<workspace.AppConfig>;

export function ExportAIContext(arg1:string,arg2:ai.AIContextOptions):Promise<string>;

export function ExportLogs(arg1:Array<logcat.LogEntry>):Promise<string>;

export function ExportLogsJSONL(arg1:Array<logcat.LogEntry>):Promise<string>;

export function FindADB(arg1:string):Promise<string>;

export function FindLatestAPK(arg1:string):Promise<build.APKInfo>;

export function GenerateAIContext(arg1:string,arg2:ai.AIContextOptions):Promise<string>;

export function GetCurrentSessionSummary():Promise<storage.SessionSummary>;

export function GetDeviceInfo(arg1:string):Promise<adb.AndroidDevice>;

export function GetLogBatch(arg1:number,arg2:number):Promise<logcat.LogBatch>;

export function GetLogStatus():Promise<logcat.LogStatus>;

export function GetPackagePIDState():Promise<logcat.PackagePIDState>;

export function GetProjectConfig():Promise<workspace.ProjectConfig>;

export function InstallAPK(arg1:string,arg2:adb.InstallOptions):Promise<adb.InstallResult>;

export function LaunchApp(arg1:string):Promise<adb.LaunchResult>;

export function ListDevices():Promise<Array<adb.AndroidDevice>>;

export function ListFilterPresets():Promise<Array<workspace.FilterPreset>>;

export function ListPackages(arg1:string,arg2:string):Promise<Array<adb.InstalledPackage>>;

export function ListWorkspaces():Promise<Array<workspace.WorkspaceConfig>>;

export function LoadConfig():Promise<workspace.AppConfig>;

export function LoadOfflineLogFile(arg1:string):Promise<logcat.OfflineLogFileResult>;

export function OpenLogFile(arg1:string):Promise<logcat.OfflineLogFileResult>;

export function OpenSession(arg1:string):Promise<main.SessionOpenResult>;

export function ResetConfig():Promise<workspace.AppConfig>;

export function ReturnToLiveMode():Promise<void>;

export function SaveConfig(arg1:workspace.AppConfig):Promise<void>;

export function SaveFilterPreset(arg1:workspace.FilterPreset):Promise<workspace.AppConfig>;

export function SaveProjectConfig(arg1:workspace.ProjectConfig):Promise<void>;

export function SaveSession(arg1:string,arg2:main.SessionSaveOptions):Promise<storage.SessionSummary>;

export function SaveWorkspace(arg1:workspace.WorkspaceConfig):Promise<workspace.AppConfig>;

export function SelectADBExecutable():Promise<string>;

export function SelectProjectDirectory():Promise<string>;

export function SetActiveDevice(arg1:string):Promise<void>;

export function SetActiveWorkspace(arg1:string):Promise<workspace.AppConfig>;

export function SetTrackedPackage(arg1:string,arg2:string):Promise<void>;

export function StartLogcat(arg1:string):Promise<void>;

export function StopLogcat():Promise<void>;

export function UseADBPath(arg1:string):Promise<string>;
