// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logcat} from '../models';
import {ai} from '../models';
import {adb} from '../models';

export function AnalyzeLogs(arg1:Array<logcat.LogEntry>):Promise<Array<logcat.AnalysisResult>>;

export function ClearLogs():Promise<void>;

export function CopyAIContext(arg1:string,arg2:ai.AIContextOptions):Promise<void>;

export function ExportAIContext(arg1:string,arg2:ai.AIContextOptions):Promise<string>;

export function ExportLogs(arg1:Array<logcat.LogEntry>):Promise<string>;

export function FindADB(arg1:string):Promise<string>;

export function GenerateAIContext(arg1:string,arg2:ai.AIContextOptions):Promise<string>;

export function GetDeviceInfo(arg1:string):Promise<adb.AndroidDevice>;

export function GetLogBatch(arg1:number,arg2:number):Promise<logcat.LogBatch>;

export function GetLogStatus():Promise<logcat.LogStatus>;

export function GetPackagePIDState():Promise<logcat.PackagePIDState>;

export function ListDevices():Promise<Array<adb.AndroidDevice>>;

export function ListPackages(arg1:string,arg2:string):Promise<Array<adb.InstalledPackage>>;

export function SetTrackedPackage(arg1:string,arg2:string):Promise<void>;

export function StartLogcat(arg1:string):Promise<void>;

export function StopLogcat():Promise<void>;
