// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeLogs(arg1) {
  return window['go']['main']['App']['AnalyzeLogs'](arg1);
}

export function BuildDebug(arg1) {
  return window['go']['main']['App']['BuildDebug'](arg1);
}

export function BuildInstallLaunch(arg1) {
  return window['go']['main']['App']['BuildInstallLaunch'](arg1);
}

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CopyAIContext(arg1, arg2) {
  return window['go']['main']['App']['CopyAIContext'](arg1, arg2);
}

export function DeleteFilterPreset(arg1) {
  return window['go']['main']['App']['DeleteFilterPreset'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function ExportAIContext(arg1, arg2) {
  return window['go']['main']['App']['ExportAIContext'](arg1, arg2);
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}

export function ExportLogsJSONL(arg1) {
  return window['go']['main']['App']['ExportLogsJSONL'](arg1);
}

export function FindADB(arg1) {
  return window['go']['main']['App']['FindADB'](arg1);
}

export function FindLatestAPK(arg1) {
  return window['go']['main']['App']['FindLatestAPK'](arg1);
}

export function GenerateAIContext(arg1, arg2) {
  return window['go']['main']['App']['GenerateAIContext'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCurrentSessionSummary() {
  return window['go']['main']['App']['GetCurrentSessionSummary']();
}

export function GetDeviceInfo(arg1) {
  return window['go']['main']['App']['GetDeviceInfo'](arg1);
}

export function GetLogBatch(arg1, arg2) {
  return window['go']['main']['App']['GetLogBatch'](arg1, arg2);
}

export function GetLogStatus() {
  return window['go']['main']['App']['GetLogStatus']();
}

export function GetPackagePIDState() {
  return window['go']['main']['App']['GetPackagePIDState']();
}

export function GetProjectConfig() {
  return window['go']['main']['App']['GetProjectConfig']();
}

export function InstallAPK(arg1, arg2) {
  return window['go']['main']['App']['InstallAPK'](arg1, arg2);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListFilterPresets() {
  return window['go']['main']['App']['ListFilterPresets']();
}

export function ListPackages(arg1, arg2) {
  return window['go']['main']['App']['ListPackages'](arg1, arg2);
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadOfflineLogFile(arg1) {
  return window['go']['main']['App']['LoadOfflineLogFile'](arg1);
}

export function OpenLogFile(arg1) {
  return window['go']['main']['App']['OpenLogFile'](arg1);
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['App']['OpenReleasePage'](arg1);
}

export function OpenSession(arg1) {
  return window['go']['main']['App']['OpenSession'](arg1);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function ReturnToLiveMode() {
  return window['go']['main']['App']['ReturnToLiveMode']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFilterPreset(arg1) {
  return window['go']['main']['App']['SaveFilterPreset'](arg1);
}

export function SaveProjectConfig(arg1) {
  return window['go']['main']['App']['SaveProjectConfig'](arg1);
}

export function SaveSession(arg1, arg2) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2);
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}

export function SelectADBExecutable() {
  return window['go']['main']['App']['SelectADBExecutable']();
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function SetActiveDevice(arg1) {
  return window['go']['main']['App']['SetActiveDevice'](arg1);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['main']['App']['SetActiveWorkspace'](arg1);
}

export function SetTrackedPackage(arg1, arg2) {
  return window['go']['main']['App']['SetTrackedPackage'](arg1, arg2);
}

export function StartLogcat(arg1) {
  return window['go']['main']['App']['StartLogcat'](arg1);
}

export function StopLogcat() {
  return window['go']['main']['App']['StopLogcat']();
}

export function UseADBPath(arg1) {
  return window['go']['main']['App']['UseADBPath'](arg1);
}
