// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeLogs(arg1) {
  return window['go']['main']['App']['AnalyzeLogs'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}

export function FindADB(arg1) {
  return window['go']['main']['App']['FindADB'](arg1);
}

export function GetDeviceInfo(arg1) {
  return window['go']['main']['App']['GetDeviceInfo'](arg1);
}

export function GetLogBatch(arg1, arg2) {
  return window['go']['main']['App']['GetLogBatch'](arg1, arg2);
}

export function GetLogStatus() {
  return window['go']['main']['App']['GetLogStatus']();
}

export function GetPackagePIDState() {
  return window['go']['main']['App']['GetPackagePIDState']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListPackages(arg1, arg2) {
  return window['go']['main']['App']['ListPackages'](arg1, arg2);
}

export function SetTrackedPackage(arg1, arg2) {
  return window['go']['main']['App']['SetTrackedPackage'](arg1, arg2);
}

export function StartLogcat(arg1) {
  return window['go']['main']['App']['StartLogcat'](arg1);
}

export function StopLogcat() {
  return window['go']['main']['App']['StopLogcat']();
}
